//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MVCProjectModel", "fk_designationId", "Designation", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCProject.Api.Models.Designation), "TblEmployee", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCProject.Api.Models.TblEmployee), true)]
[assembly: EdmRelationshipAttribute("MVCProjectModel", "fk_despartmentId", "TblDepartment", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCProject.Api.Models.TblDepartment), "TblEmployee", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCProject.Api.Models.TblEmployee), true)]
[assembly: EdmRelationshipAttribute("MVCProjectModel", "fk_EmployeeId", "TblEmployee", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCProject.Api.Models.TblEmployee), "Attendance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCProject.Api.Models.Attendance), true)]

#endregion

namespace MVCProject.Api.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MVCProjectEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MVCProjectEntities object using the connection string found in the 'MVCProjectEntities' section of the application configuration file.
        /// </summary>
        public MVCProjectEntities() : base("name=MVCProjectEntities", "MVCProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MVCProjectEntities object.
        /// </summary>
        public MVCProjectEntities(string connectionString) : base(connectionString, "MVCProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MVCProjectEntities object.
        /// </summary>
        public MVCProjectEntities(EntityConnection connection) : base(connection, "MVCProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Designation> Designations
        {
            get
            {
                if ((_Designations == null))
                {
                    _Designations = base.CreateObjectSet<Designation>("Designations");
                }
                return _Designations;
            }
        }
        private ObjectSet<Designation> _Designations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblDepartment> TblDepartments
        {
            get
            {
                if ((_TblDepartments == null))
                {
                    _TblDepartments = base.CreateObjectSet<TblDepartment>("TblDepartments");
                }
                return _TblDepartments;
            }
        }
        private ObjectSet<TblDepartment> _TblDepartments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblEmployee> TblEmployees
        {
            get
            {
                if ((_TblEmployees == null))
                {
                    _TblEmployees = base.CreateObjectSet<TblEmployee>("TblEmployees");
                }
                return _TblEmployees;
            }
        }
        private ObjectSet<TblEmployee> _TblEmployees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Attendance> Attendance
        {
            get
            {
                if ((_Attendance == null))
                {
                    _Attendance = base.CreateObjectSet<Attendance>("Attendance");
                }
                return _Attendance;
            }
        }
        private ObjectSet<Attendance> _Attendance;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AttachmentMaster> AttachmentMaster
        {
            get
            {
                if ((_AttachmentMaster == null))
                {
                    _AttachmentMaster = base.CreateObjectSet<AttachmentMaster>("AttachmentMaster");
                }
                return _AttachmentMaster;
            }
        }
        private ObjectSet<AttachmentMaster> _AttachmentMaster;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AttachmentType> AttachmentType
        {
            get
            {
                if ((_AttachmentType == null))
                {
                    _AttachmentType = base.CreateObjectSet<AttachmentType>("AttachmentType");
                }
                return _AttachmentType;
            }
        }
        private ObjectSet<AttachmentType> _AttachmentType;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Designations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDesignations(Designation designation)
        {
            base.AddObject("Designations", designation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblDepartments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblDepartments(TblDepartment tblDepartment)
        {
            base.AddObject("TblDepartments", tblDepartment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblEmployees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblEmployees(TblEmployee tblEmployee)
        {
            base.AddObject("TblEmployees", tblEmployee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Attendance EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAttendance(Attendance attendance)
        {
            base.AddObject("Attendance", attendance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AttachmentMaster EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAttachmentMaster(AttachmentMaster attachmentMaster)
        {
            base.AddObject("AttachmentMaster", attachmentMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AttachmentType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAttachmentType(AttachmentType attachmentType)
        {
            base.AddObject("AttachmentType", attachmentType);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="AttachmentMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AttachmentMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AttachmentMaster object.
        /// </summary>
        /// <param name="attachmentId">Initial value of the AttachmentId property.</param>
        public static AttachmentMaster CreateAttachmentMaster(global::System.Int32 attachmentId)
        {
            AttachmentMaster attachmentMaster = new AttachmentMaster();
            attachmentMaster.AttachmentId = attachmentId;
            return attachmentMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttachmentId
        {
            get
            {
                return _AttachmentId;
            }
            set
            {
                if (_AttachmentId != value)
                {
                    OnAttachmentIdChanging(value);
                    ReportPropertyChanging("AttachmentId");
                    _AttachmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AttachmentId");
                    OnAttachmentIdChanged();
                }
            }
        }
        private global::System.Int32 _AttachmentId;
        partial void OnAttachmentIdChanging(global::System.Int32 value);
        partial void OnAttachmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Filepath
        {
            get
            {
                return _Filepath;
            }
            set
            {
                OnFilepathChanging(value);
                ReportPropertyChanging("Filepath");
                _Filepath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Filepath");
                OnFilepathChanged();
            }
        }
        private global::System.String _Filepath;
        partial void OnFilepathChanging(global::System.String value);
        partial void OnFilepathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileAttachmentType
        {
            get
            {
                return _FileAttachmentType;
            }
            set
            {
                OnFileAttachmentTypeChanging(value);
                ReportPropertyChanging("FileAttachmentType");
                _FileAttachmentType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileAttachmentType");
                OnFileAttachmentTypeChanged();
            }
        }
        private global::System.String _FileAttachmentType;
        partial void OnFileAttachmentTypeChanging(global::System.String value);
        partial void OnFileAttachmentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDeleted;
        partial void OnIsDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RefrencedId
        {
            get
            {
                return _RefrencedId;
            }
            set
            {
                OnRefrencedIdChanging(value);
                ReportPropertyChanging("RefrencedId");
                _RefrencedId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RefrencedId");
                OnRefrencedIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RefrencedId;
        partial void OnRefrencedIdChanging(Nullable<global::System.Int32> value);
        partial void OnRefrencedIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="AttachmentType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AttachmentType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AttachmentType object.
        /// </summary>
        /// <param name="attachmentTypeId">Initial value of the AttachmentTypeId property.</param>
        public static AttachmentType CreateAttachmentType(global::System.Int32 attachmentTypeId)
        {
            AttachmentType attachmentType = new AttachmentType();
            attachmentType.AttachmentTypeId = attachmentTypeId;
            return attachmentType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttachmentTypeId
        {
            get
            {
                return _AttachmentTypeId;
            }
            set
            {
                if (_AttachmentTypeId != value)
                {
                    OnAttachmentTypeIdChanging(value);
                    ReportPropertyChanging("AttachmentTypeId");
                    _AttachmentTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AttachmentTypeId");
                    OnAttachmentTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _AttachmentTypeId;
        partial void OnAttachmentTypeIdChanging(global::System.Int32 value);
        partial void OnAttachmentTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AttachmentTypeName
        {
            get
            {
                return _AttachmentTypeName;
            }
            set
            {
                OnAttachmentTypeNameChanging(value);
                ReportPropertyChanging("AttachmentTypeName");
                _AttachmentTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AttachmentTypeName");
                OnAttachmentTypeNameChanged();
            }
        }
        private global::System.String _AttachmentTypeName;
        partial void OnAttachmentTypeNameChanging(global::System.String value);
        partial void OnAttachmentTypeNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="Attendance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Attendance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Attendance object.
        /// </summary>
        /// <param name="attendanceId">Initial value of the AttendanceId property.</param>
        public static Attendance CreateAttendance(global::System.Int32 attendanceId)
        {
            Attendance attendance = new Attendance();
            attendance.AttendanceId = attendanceId;
            return attendance;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttendanceId
        {
            get
            {
                return _AttendanceId;
            }
            set
            {
                if (_AttendanceId != value)
                {
                    OnAttendanceIdChanging(value);
                    ReportPropertyChanging("AttendanceId");
                    _AttendanceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AttendanceId");
                    OnAttendanceIdChanged();
                }
            }
        }
        private global::System.Int32 _AttendanceId;
        partial void OnAttendanceIdChanging(global::System.Int32 value);
        partial void OnAttendanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                OnEmployeeIdChanging(value);
                ReportPropertyChanging("EmployeeId");
                _EmployeeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeId");
                OnEmployeeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _EmployeeId;
        partial void OnEmployeeIdChanging(Nullable<global::System.Int32> value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartingTime
        {
            get
            {
                return _StartingTime;
            }
            set
            {
                OnStartingTimeChanging(value);
                ReportPropertyChanging("StartingTime");
                _StartingTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartingTime");
                OnStartingTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartingTime;
        partial void OnStartingTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartingTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndingTime
        {
            get
            {
                return _EndingTime;
            }
            set
            {
                OnEndingTimeChanging(value);
                ReportPropertyChanging("EndingTime");
                _EndingTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndingTime");
                OnEndingTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndingTime;
        partial void OnEndingTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndingTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StartingLatitude
        {
            get
            {
                return _StartingLatitude;
            }
            set
            {
                OnStartingLatitudeChanging(value);
                ReportPropertyChanging("StartingLatitude");
                _StartingLatitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartingLatitude");
                OnStartingLatitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _StartingLatitude;
        partial void OnStartingLatitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnStartingLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> EndingLatitude
        {
            get
            {
                return _EndingLatitude;
            }
            set
            {
                OnEndingLatitudeChanging(value);
                ReportPropertyChanging("EndingLatitude");
                _EndingLatitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndingLatitude");
                OnEndingLatitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _EndingLatitude;
        partial void OnEndingLatitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnEndingLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StartingLongitude
        {
            get
            {
                return _StartingLongitude;
            }
            set
            {
                OnStartingLongitudeChanging(value);
                ReportPropertyChanging("StartingLongitude");
                _StartingLongitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartingLongitude");
                OnStartingLongitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _StartingLongitude;
        partial void OnStartingLongitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnStartingLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> EndingLongitude
        {
            get
            {
                return _EndingLongitude;
            }
            set
            {
                OnEndingLongitudeChanging(value);
                ReportPropertyChanging("EndingLongitude");
                _EndingLongitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndingLongitude");
                OnEndingLongitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _EndingLongitude;
        partial void OnEndingLongitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnEndingLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EntryBy
        {
            get
            {
                return _EntryBy;
            }
            set
            {
                OnEntryByChanging(value);
                ReportPropertyChanging("EntryBy");
                _EntryBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryBy");
                OnEntryByChanged();
            }
        }
        private Nullable<global::System.Int32> _EntryBy;
        partial void OnEntryByChanging(Nullable<global::System.Int32> value);
        partial void OnEntryByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EntryDate;
        partial void OnEntryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdatedBy;
        partial void OnUpdatedByChanging(Nullable<global::System.Int32> value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedDate;
        partial void OnUpdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Discription
        {
            get
            {
                return _Discription;
            }
            set
            {
                OnDiscriptionChanging(value);
                ReportPropertyChanging("Discription");
                _Discription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Discription");
                OnDiscriptionChanged();
            }
        }
        private global::System.String _Discription;
        partial void OnDiscriptionChanging(global::System.String value);
        partial void OnDiscriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "fk_EmployeeId", "TblEmployee")]
        public TblEmployee TblEmployee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblEmployee>("MVCProjectModel.fk_EmployeeId", "TblEmployee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblEmployee>("MVCProjectModel.fk_EmployeeId", "TblEmployee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblEmployee> TblEmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblEmployee>("MVCProjectModel.fk_EmployeeId", "TblEmployee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblEmployee>("MVCProjectModel.fk_EmployeeId", "TblEmployee", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="Designation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Designation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Designation object.
        /// </summary>
        /// <param name="designationId">Initial value of the DesignationId property.</param>
        public static Designation CreateDesignation(global::System.Int32 designationId)
        {
            Designation designation = new Designation();
            designation.DesignationId = designationId;
            return designation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DesignationId
        {
            get
            {
                return _DesignationId;
            }
            set
            {
                if (_DesignationId != value)
                {
                    OnDesignationIdChanging(value);
                    ReportPropertyChanging("DesignationId");
                    _DesignationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DesignationId");
                    OnDesignationIdChanged();
                }
            }
        }
        private global::System.Int32 _DesignationId;
        partial void OnDesignationIdChanging(global::System.Int32 value);
        partial void OnDesignationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DesignationName
        {
            get
            {
                return _DesignationName;
            }
            set
            {
                OnDesignationNameChanging(value);
                ReportPropertyChanging("DesignationName");
                _DesignationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DesignationName");
                OnDesignationNameChanged();
            }
        }
        private global::System.String _DesignationName;
        partial void OnDesignationNameChanging(global::System.String value);
        partial void OnDesignationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "fk_designationId", "TblEmployee")]
        public EntityCollection<TblEmployee> TblEmployees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblEmployee>("MVCProjectModel.fk_designationId", "TblEmployee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblEmployee>("MVCProjectModel.fk_designationId", "TblEmployee", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="TblDepartment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblDepartment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblDepartment object.
        /// </summary>
        /// <param name="departmentId">Initial value of the DepartmentId property.</param>
        /// <param name="departmentName">Initial value of the DepartmentName property.</param>
        public static TblDepartment CreateTblDepartment(global::System.Int32 departmentId, global::System.String departmentName)
        {
            TblDepartment tblDepartment = new TblDepartment();
            tblDepartment.DepartmentId = departmentId;
            tblDepartment.DepartmentName = departmentName;
            return tblDepartment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentId
        {
            get
            {
                return _DepartmentId;
            }
            set
            {
                if (_DepartmentId != value)
                {
                    OnDepartmentIdChanging(value);
                    ReportPropertyChanging("DepartmentId");
                    _DepartmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DepartmentId");
                    OnDepartmentIdChanged();
                }
            }
        }
        private global::System.Int32 _DepartmentId;
        partial void OnDepartmentIdChanging(global::System.Int32 value);
        partial void OnDepartmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EntryById
        {
            get
            {
                return _EntryById;
            }
            set
            {
                OnEntryByIdChanging(value);
                ReportPropertyChanging("EntryById");
                _EntryById = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryById");
                OnEntryByIdChanged();
            }
        }
        private Nullable<global::System.Int32> _EntryById;
        partial void OnEntryByIdChanging(Nullable<global::System.Int32> value);
        partial void OnEntryByIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EntryDate;
        partial void OnEntryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdateBy
        {
            get
            {
                return _UpdateBy;
            }
            set
            {
                OnUpdateByChanging(value);
                ReportPropertyChanging("UpdateBy");
                _UpdateBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateBy");
                OnUpdateByChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdateBy;
        partial void OnUpdateByChanging(Nullable<global::System.Int32> value);
        partial void OnUpdateByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedDate;
        partial void OnUpdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "fk_despartmentId", "TblEmployee")]
        public EntityCollection<TblEmployee> TblEmployees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblEmployee>("MVCProjectModel.fk_despartmentId", "TblEmployee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblEmployee>("MVCProjectModel.fk_despartmentId", "TblEmployee", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="TblEmployee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblEmployee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblEmployee object.
        /// </summary>
        /// <param name="employeeId">Initial value of the EmployeeId property.</param>
        public static TblEmployee CreateTblEmployee(global::System.Int32 employeeId)
        {
            TblEmployee tblEmployee = new TblEmployee();
            tblEmployee.EmployeeId = employeeId;
            return tblEmployee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                if (_EmployeeId != value)
                {
                    OnEmployeeIdChanging(value);
                    ReportPropertyChanging("EmployeeId");
                    _EmployeeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeId");
                    OnEmployeeIdChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeId;
        partial void OnEmployeeIdChanging(global::System.Int32 value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> JoiningDate
        {
            get
            {
                return _JoiningDate;
            }
            set
            {
                OnJoiningDateChanging(value);
                ReportPropertyChanging("JoiningDate");
                _JoiningDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JoiningDate");
                OnJoiningDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _JoiningDate;
        partial void OnJoiningDateChanging(Nullable<global::System.DateTime> value);
        partial void OnJoiningDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AlternatePhoneNumber
        {
            get
            {
                return _AlternatePhoneNumber;
            }
            set
            {
                OnAlternatePhoneNumberChanging(value);
                ReportPropertyChanging("AlternatePhoneNumber");
                _AlternatePhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AlternatePhoneNumber");
                OnAlternatePhoneNumberChanged();
            }
        }
        private global::System.String _AlternatePhoneNumber;
        partial void OnAlternatePhoneNumberChanging(global::System.String value);
        partial void OnAlternatePhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DesignationId
        {
            get
            {
                return _DesignationId;
            }
            set
            {
                OnDesignationIdChanging(value);
                ReportPropertyChanging("DesignationId");
                _DesignationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DesignationId");
                OnDesignationIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DesignationId;
        partial void OnDesignationIdChanging(Nullable<global::System.Int32> value);
        partial void OnDesignationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProfileImageName
        {
            get
            {
                return _ProfileImageName;
            }
            set
            {
                OnProfileImageNameChanging(value);
                ReportPropertyChanging("ProfileImageName");
                _ProfileImageName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProfileImageName");
                OnProfileImageNameChanged();
            }
        }
        private global::System.String _ProfileImageName;
        partial void OnProfileImageNameChanging(global::System.String value);
        partial void OnProfileImageNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DepartmentId
        {
            get
            {
                return _DepartmentId;
            }
            set
            {
                OnDepartmentIdChanging(value);
                ReportPropertyChanging("DepartmentId");
                _DepartmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentId");
                OnDepartmentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DepartmentId;
        partial void OnDepartmentIdChanging(Nullable<global::System.Int32> value);
        partial void OnDepartmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BirthDate
        {
            get
            {
                return _BirthDate;
            }
            set
            {
                OnBirthDateChanging(value);
                ReportPropertyChanging("BirthDate");
                _BirthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BirthDate");
                OnBirthDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BirthDate;
        partial void OnBirthDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PermanentAddress
        {
            get
            {
                return _PermanentAddress;
            }
            set
            {
                OnPermanentAddressChanging(value);
                ReportPropertyChanging("PermanentAddress");
                _PermanentAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PermanentAddress");
                OnPermanentAddressChanged();
            }
        }
        private global::System.String _PermanentAddress;
        partial void OnPermanentAddressChanging(global::System.String value);
        partial void OnPermanentAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TemporaryAddress
        {
            get
            {
                return _TemporaryAddress;
            }
            set
            {
                OnTemporaryAddressChanging(value);
                ReportPropertyChanging("TemporaryAddress");
                _TemporaryAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TemporaryAddress");
                OnTemporaryAddressChanged();
            }
        }
        private global::System.String _TemporaryAddress;
        partial void OnTemporaryAddressChanging(global::System.String value);
        partial void OnTemporaryAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pincode
        {
            get
            {
                return _Pincode;
            }
            set
            {
                OnPincodeChanging(value);
                ReportPropertyChanging("Pincode");
                _Pincode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pincode");
                OnPincodeChanged();
            }
        }
        private Nullable<global::System.Int32> _Pincode;
        partial void OnPincodeChanging(Nullable<global::System.Int32> value);
        partial void OnPincodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InstitutionName
        {
            get
            {
                return _InstitutionName;
            }
            set
            {
                OnInstitutionNameChanging(value);
                ReportPropertyChanging("InstitutionName");
                _InstitutionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InstitutionName");
                OnInstitutionNameChanged();
            }
        }
        private global::System.String _InstitutionName;
        partial void OnInstitutionNameChanging(global::System.String value);
        partial void OnInstitutionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseName
        {
            get
            {
                return _CourseName;
            }
            set
            {
                OnCourseNameChanging(value);
                ReportPropertyChanging("CourseName");
                _CourseName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseName");
                OnCourseNameChanged();
            }
        }
        private global::System.String _CourseName;
        partial void OnCourseNameChanging(global::System.String value);
        partial void OnCourseNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CourseStartDate
        {
            get
            {
                return _CourseStartDate;
            }
            set
            {
                OnCourseStartDateChanging(value);
                ReportPropertyChanging("CourseStartDate");
                _CourseStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CourseStartDate");
                OnCourseStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CourseStartDate;
        partial void OnCourseStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCourseStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CourseEndDate
        {
            get
            {
                return _CourseEndDate;
            }
            set
            {
                OnCourseEndDateChanging(value);
                ReportPropertyChanging("CourseEndDate");
                _CourseEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CourseEndDate");
                OnCourseEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CourseEndDate;
        partial void OnCourseEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCourseEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Grade
        {
            get
            {
                return _Grade;
            }
            set
            {
                OnGradeChanging(value);
                ReportPropertyChanging("Grade");
                _Grade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Grade");
                OnGradeChanged();
            }
        }
        private global::System.String _Grade;
        partial void OnGradeChanging(global::System.String value);
        partial void OnGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Degree
        {
            get
            {
                return _Degree;
            }
            set
            {
                OnDegreeChanging(value);
                ReportPropertyChanging("Degree");
                _Degree = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Degree");
                OnDegreeChanged();
            }
        }
        private global::System.String _Degree;
        partial void OnDegreeChanging(global::System.String value);
        partial void OnDegreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastJobLocation
        {
            get
            {
                return _LastJobLocation;
            }
            set
            {
                OnLastJobLocationChanging(value);
                ReportPropertyChanging("LastJobLocation");
                _LastJobLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastJobLocation");
                OnLastJobLocationChanged();
            }
        }
        private global::System.String _LastJobLocation;
        partial void OnLastJobLocationChanging(global::System.String value);
        partial void OnLastJobLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JobPosition
        {
            get
            {
                return _JobPosition;
            }
            set
            {
                OnJobPositionChanging(value);
                ReportPropertyChanging("JobPosition");
                _JobPosition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JobPosition");
                OnJobPositionChanged();
            }
        }
        private global::System.String _JobPosition;
        partial void OnJobPositionChanging(global::System.String value);
        partial void OnJobPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FromPeriod
        {
            get
            {
                return _FromPeriod;
            }
            set
            {
                OnFromPeriodChanging(value);
                ReportPropertyChanging("FromPeriod");
                _FromPeriod = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromPeriod");
                OnFromPeriodChanged();
            }
        }
        private Nullable<global::System.DateTime> _FromPeriod;
        partial void OnFromPeriodChanging(Nullable<global::System.DateTime> value);
        partial void OnFromPeriodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ToPeriod
        {
            get
            {
                return _ToPeriod;
            }
            set
            {
                OnToPeriodChanging(value);
                ReportPropertyChanging("ToPeriod");
                _ToPeriod = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToPeriod");
                OnToPeriodChanged();
            }
        }
        private Nullable<global::System.DateTime> _ToPeriod;
        partial void OnToPeriodChanging(Nullable<global::System.DateTime> value);
        partial void OnToPeriodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private Nullable<global::System.Int32> _Gender;
        partial void OnGenderChanging(Nullable<global::System.Int32> value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EntryBy
        {
            get
            {
                return _EntryBy;
            }
            set
            {
                OnEntryByChanging(value);
                ReportPropertyChanging("EntryBy");
                _EntryBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryBy");
                OnEntryByChanged();
            }
        }
        private Nullable<global::System.Int32> _EntryBy;
        partial void OnEntryByChanging(Nullable<global::System.Int32> value);
        partial void OnEntryByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EntryDate;
        partial void OnEntryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdatedBy;
        partial void OnUpdatedByChanging(Nullable<global::System.Int32> value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedDate;
        partial void OnUpdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "fk_designationId", "Designation")]
        public Designation Designation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Designation>("MVCProjectModel.fk_designationId", "Designation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Designation>("MVCProjectModel.fk_designationId", "Designation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Designation> DesignationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Designation>("MVCProjectModel.fk_designationId", "Designation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Designation>("MVCProjectModel.fk_designationId", "Designation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "fk_despartmentId", "TblDepartment")]
        public TblDepartment TblDepartment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblDepartment>("MVCProjectModel.fk_despartmentId", "TblDepartment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblDepartment>("MVCProjectModel.fk_despartmentId", "TblDepartment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblDepartment> TblDepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblDepartment>("MVCProjectModel.fk_despartmentId", "TblDepartment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblDepartment>("MVCProjectModel.fk_despartmentId", "TblDepartment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "fk_EmployeeId", "Attendance")]
        public EntityCollection<Attendance> Attendance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Attendance>("MVCProjectModel.fk_EmployeeId", "Attendance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Attendance>("MVCProjectModel.fk_EmployeeId", "Attendance", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
